utils::globalVariables(c("X",
                         "errcodes",
                         "nodes_and_cohorts",
                         "node_name",
                         "error_code",
                         "opals",
                         "node",
                         "name",
                         "cohort"))
